obj_string += $(addprefix $(BUILD_DIR)libc/string/, \
	memcmp.o \
	memcpy.o \
	memmove.o \
	memset.o \
	strlen.o \
	strrev.o \
)

obj += $(obj_string)

obj_stdlib += $(addprefix $(BUILD_DIR)libc/stdlib/, \
	itoa.o \
)

obj += $(obj_stdlib)
